# Generated by Django 2.1.1 on 2019-01-25 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='update_table',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ph', models.CharField(max_length=250)),
                ('alcohol_content', models.CharField(max_length=250)),
                ('temperature', models.CharField(max_length=250)),
                ('volatile_acid', models.CharField(max_length=250)),
            ],
        ),
        migrations.RenameModel(
            old_name='fruitwine_table',
            new_name='history_table',
        ),
    ]
