# Generated by Django 2.1.1 on 2019-01-28 16:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20190129_0016'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='history_table',
            name='date_time',
        ),
    ]
