# Generated by Django 2.1.1 on 2019-01-28 16:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_history_table_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='history_table',
            name='time',
        ),
    ]
