# Generated by Django 2.1.1 on 2019-01-28 16:58

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_remove_history_table_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='history_table',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
