# Generated by Django 2.1.1 on 2019-01-28 17:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_history_table_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='history_table',
            name='created_at',
        ),
    ]
