# Generated by Django 2.1.1 on 2019-02-10 04:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_auto_20190208_1544'),
    ]

    operations = [
        migrations.AlterField(
            model_name='history_table',
            name='uploaded',
            field=models.DateTimeField(default=datetime.datetime(2019, 2, 10, 12, 36, 47, 172492)),
        ),
        migrations.AlterField(
            model_name='update_table',
            name='uploaded',
            field=models.DateTimeField(default=datetime.datetime(2019, 2, 10, 12, 36, 47, 154534)),
        ),
    ]
