# Generated by Django 2.1.1 on 2019-02-10 18:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_auto_20190210_1236'),
        ('api', '0011_auto_20190210_0119'),
    ]

    operations = [
    ]
