# Generated by Django 2.1.1 on 2019-02-10 18:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_auto_20190211_0220'),
    ]

    operations = [
        migrations.AlterField(
            model_name='history_table',
            name='uploaded',
            field=models.DateTimeField(default=datetime.datetime(2019, 2, 11, 2, 22, 55, 557447)),
        ),
        migrations.AlterField(
            model_name='update_table',
            name='uploaded',
            field=models.DateTimeField(default=datetime.datetime(2019, 2, 11, 2, 22, 55, 540402)),
        ),
    ]
